apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-native
  labels:
    name: cloud-native
spec:
  selector:
    matchLabels:
      name: cloud-native
  replicas: 1
  template:
    metadata:
      labels:
        name: cloud-native
    spec:
      containers:
        - name: cloud-native
          image: walkerrandolphsmith/cloud-native-logging:2.0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-native
  labels:
    name: cloud-native
spec:
  type: NodePort
  ports:
    - port: 3000
  selector:
    name: cloud-native
