apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    name: api
    maturityStage: dev
    release: stable
spec:
  type: NodePort # Expose to outside the cluster on <NodeIP>:<NodePort>
  ports:
    - port: 3000 # targetPort field defaults to this value as well
  selector:
    name: api
