apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api
        version: v2.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
    spec:
      containers:
        - name: api
          image: walkerrandolphsmith/k8s-deployment-strategies:2.0
          ports:
            - name: http
              containerPort: 3000
            - name: probe
              containerPort: 3001
          livenessProbe:
            httpGet:
              path: /live
              port: probe
            initialDelaySeconds: 11
            periodSeconds: 11
            timeoutSeconds: 11
            failureThreshold: 11
          readinessProbe:
            httpGet:
              path: /ready
              port: probe
            initialDelaySeconds: 11
            periodSeconds: 11
            timeoutSeconds: 11
            failureThreshold: 11
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "100m"
