version: "3.4"

networks:
  webnet:
  intranet:

volumes:
  data-db:

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment: 
      PORT: "3000"
      MONGO_URI: "mongodb://db:27017/dev-db"
    networks: 
      - webnet
      - intranet
    depends_on:
      - db
  db:
    image: mongo
    networks:
      - intranet
    volumes:
      - data-db:/data/db
  db-ui:
    image: mongo-express
    ports:
      - 8081:8081
    networks:
      - intranet
      - webnet
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: db
    depends_on:
      - db