apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    name: api
spec:
  selector:
    matchLabels:
      name: api
  replicas: 2
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
        - name: api
          image: walkerrandolphsmith/stateful-workload-api:4.0
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/dev?replicaSet=rs0"
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    name: api
spec:
  type: LoadBalancer
  ports:
    - port: 3001
      targetPort: 3000
      protocol: TCP
  selector:
    name: api
