---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    name: api
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    name: api
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-test
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "session"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"

spec:
  rules:
    - host: session-affinity.com
      http:
        paths:
          - path: /
            backend:
              serviceName: api
              servicePort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    name: api
    maturityStage: dev
    release: stable
    teir: backend

spec:
  selector:
    matchLabels:
      name: api
  replicas: 3
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
        - name: api-container
          image: walkerrandolphsmith/session-affinity:3.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 3000
