---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    name: api
spec:
  ports:
    - port: 4000
  selector:
    name: api
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
spec:
  rules:
    - host: monitored.api.com
      http:
        paths:
          - path: /
            backend:
              serviceName: api
              servicePort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    name: api
    maturityStage: dev
    release: stable
    teir: backend
spec:
  selector:
    matchLabels:
      name: api
  replicas: 4
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
        - name: api-container
          image: walkerrandolphsmith/monitored-api:3.0
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: app
              containerPort: 4000
