---
apiVersion: v1
kind: Service
metadata:
  name: service-0
  labels:
    name: service-0
spec:
  ports:
    - port: 3000
      targetPort: 3000
  # clusterIP: None
  selector:
    statefulset.kubernetes.io/pod-name: service-0
  externalTrafficPolicy: Local
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: service
  labels:
    name: service
spec:
  serviceName: "service"
  replicas: 3
  selector:
    matchLabels:
      name: service
  template:
    metadata:
      labels:
        name: service
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: service
          image: walkerrandolphsmith/legacy-logging:3.0
          lifecycle:
            postStart:
              exec:
                command:
                  [
                    "/bin/sh",
                    "-c",
                    "touch /var/log/legacy-logging/lifecycle.log && echo Hello from the postStart handler > /var/log/legacy-logging/lifecycle.log",
                  ]
            preStop:
              exec:
                command:
                  [
                    "/bin/sh",
                    "-c",
                    "echo Hello from the preStop handler > /var/log/legacy-logging/lifecycle.log",
                  ]
          ports:
            - containerPort: 3000
          env:
            - name: LOG_PATH
              value: /var/log/legacy-logging
            - name: LOG_FILE
              value: request.log
          volumeMounts:
            - name: logs
              mountPath: "/var/log/legacy-logging"
      volumes:
        - name: logs
  volumeClaimTemplates:
    - metadata:
        name: logger-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
