version: "3.4"

networks:
  kafka-net:

volumes:
    kafka-broker-1:
    kafka-broker-2:

services:
    producer:
        build:
            context: ./api
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        networks:
            - kafka-net
        environment:
            KAFKA_HOST: "kafka-broker-1:9092,kafka-broker-2:9093"
            DEBUG: "kafka-node:*"
        depends_on:
            - kafka-broker-1
            - kafka-broker-2
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
        networks:
            - kafka-net
    kafka-broker-1:
        image: wurstmeister/kafka
        ports:
            - 9092:9092
        environment:
            KAFKA_ADVERTISED_HOST_NAME: "kafka-broker-1"
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_BROKER_ID: 1
            KAFKA_LISTENERS: "LISTENER_INTERNAL://kafka-broker-1:9092"
            KAFKA_ADVERTISED_LISTENERS: "LISTENER_INTERNAL://kafka-broker-1:9092"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "LISTENER_INTERNAL:PLAINTEXT"
            KAFKA_INTER_BROKER_LISTENER_NAME: "LISTENER_INTERNAL"
        volumes:
            - kafka-broker-1:/var/run/docker.sock
        networks:
            - kafka-net
        depends_on:
            - zookeeper
    kafka-broker-2:
        image: wurstmeister/kafka
        ports:
            - 9093:9093
        environment:
            KAFKA_ADVERTISED_HOST_NAME: "kafka-broker-2"
            KAFKA_ADVERTISED_PORT: 9093
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_BROKER_ID: 2
            KAFKA_LISTENERS: "LISTENER_INTERNAL://kafka-broker-2:9093"
            KAFKA_ADVERTISED_LISTENERS: "LISTENER_INTERNAL://kafka-broker-2:9093"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "LISTENER_INTERNAL:PLAINTEXT"
            KAFKA_INTER_BROKER_LISTENER_NAME: "LISTENER_INTERNAL"
        volumes:
            - kafka-broker-2:/var/run/docker.sock
        networks:
            - kafka-net
        depends_on:
            - zookeeper
    kafdrop:
        image: obsidiandynamics/kafdrop
        restart: "no"
        ports:
            - "9000:9000"
        environment:
            KAFKA_BROKERCONNECT: "kafka-broker-1:9092"
            JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
        networks:
            - kafka-net
        depends_on:
            - "kafka-broker-1"